spring.thymeleaf.view-names=*,menu/*
spring.thymeleaf.prefix=classpath:/templates/thymeleaf/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false
spring.thymeleaf.check-template-location=true

spring.devtools.livereload.enabled=true
